name: Build and Publish VSCode Extension

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run compile
      
      - name: Package Extension
        run: npx @vscode/vsce package
        
      - name: Get Version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            VSCode Local Images Plus Extension v${{ steps.get_version.outputs.version }}
            
            Changes in this release:
            - Initial release
            - Support for downloading and localizing images
            - Support for converting PNG to JPEG
            - Support for cleaning orphaned files
          draft: false
          prerelease: false
          
      - name: Upload VSIX Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vscode-local-images-plus-${{ steps.get_version.outputs.version }}.vsix
          asset_name: vscode-local-images-plus-${{ steps.get_version.outputs.version }}.vsix
          asset_content_type: application/octet-stream

      - name: Publish to Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
 





